name: 'Me Geek, You Geek'
favicon: null
layout_spectrum: 0.11889817076735198
typography_spectrum: 0.7069731967058033
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.49988584709353745
  lightness: 0.46652839076705277
  saturation: 0.8998503114562482
  rhythmicContrast: 0.9303034509066492
purpose: []
